[build]
  publish = "/"
  command = "# no build command needed for simple HTML/CSS site"

[build.environment]
  NODE_VERSION = "20"

# Set cache headers for images
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Custom 404 page
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
